### ISSUE TITLE
META6 "depends" section

### ISSUE THREAD

**Issue by hythm7** [jonathanstowe/META6#21]
Does the module support the "depends" section as in [S22](https://design.raku.org/S22.html#META6.json)?

I'm testing with this META6 [file](https://github.com/niner/Inline-Perl5/blob/master/META6.json#L12-L16) and getting ```[(Str) (Str) (Str)]``` for the `depends` section.

**Comment by hythm7** [comment]
I think the issue happens because forcing `Str` type on `depends, build-depends, test-depends` although they can accept `Array` or `Hash` per S22.

Removing the `Str` and replacing `@` with `$` [here](https://github.com/jonathanstowe/META6/blob/master/lib/META6.pm#L235) for them, fixes the issue. I'd submit a PR but I'm not sure if this is the right fix.

**Comment by jonathanstowe** [comment]
Hi,
yeah that's approximately right,  it definitely needs to support either `Positional` or `Associative` and I'm just having a think about how best to do that and make it useful.

**Comment by JJ** [comment]
> I think the issue happens because forcing `Str` type on `depends, build-depends, test-depends` although they can accept `Array` or `Hash` per S22.
> 
> Removing the `Str` and replacing `@` with `$` [here](https://github.com/jonathanstowe/META6/blob/master/lib/META6.pm#L235) for them, fixes the issue. I'd submit a PR but I'm not sure if this is the right fix.

That's basically what I have done, with additional tests for this. Thanks for the suggestion.
