### ISSUE TITLE
.to-json fails if meta file doesn't have 'perl' or 'version' keys

### ISSUE THREAD

**Issue by hythm7** [jonathanstowe/META6#22]
```
my $m = META6.new: :file<META6.json>; 
say $m # works

say $m.to-json #   errors with "Don't know how to jsonify META6"

```
[META6.json](https://raw.githubusercontent.com/supernovus/perl6-http-client/master/META6.json)     doesn't have 'perl' key

**Comment by jonathanstowe** [comment]
Strangely that error is from `JSON::Fast`, but what I think is happening is that somehow `JSON::Marshal` is passing through the `META6` object to `to-json` without marshalling it to a (potentially empty,) Hash.  Which would be a bug in `JSON::Marshal` which I'll need to take a look at.

**Comment by jonathanstowe** [comment]
The fix is released in `JSON::Marshal` and will bump the required versions in the next release of `META6`.

**Comment by jonathanstowe** [comment]
It may take a while for the whole fix pulls through via CPAN
