### ISSUE TITLE
Test correct parsing of Associative depends

### ISSUE THREAD

**Issue by JJ** [jonathanstowe/META6#24]
Add a test to check that the deep data structure is parsed correctly, after ghe change in #21

**Comment by jonathanstowe** [comment]
Hi,
cheers for this.  I'll merge this, but it may be superceded by how I better deal with the polymorphic nature of the property (my current thinking is that I may use a multi un-marshaller that either returns an object or an array, both doing some base role,) and make it actually useful in the associative case.
