### ISSUE TITLE
Tests in zef fail, but pass in the repo

### ISSUE THREAD

**Issue by briandfoy** [jonathanstowe/META6#8]
I'm getting an odd failure where the tests pass in the repo but not from zef. I'm still investigating this. It looks like the repo is 0.0.16 but zef finds 0.0.11.

	brian@roscoe META6  (master)[3011]$ prove -e 'perl6 -Ilib'
	t/010-use.t .......... ok
	t/015-constructor.t .. ok
	t/020-basic.t ........ ok
	t/030-versions.t ..... ok
	t/040-projects.t ..... ok
	t/050-assoc.t ........ ok
	All tests successful.
	Files=6, Tests=50,  7 wallclock secs ( 0.05 usr  0.02 sys +  6.75 cusr  0.61 csys =  7.43 CPU)
	Result: PASS

	brian@roscoe META6  (master)[3012]$ zef install META6
	===> Searching for: META6
	===> Testing: META6:ver('0.0.11'):auth('github:jonathanstowe')
	===SORRY!=== Error while compiling /Users/brian/.zef/store/META6.git/7304270f62587c723a9aa94ce6fd601770f7d3da/t/040-projects.t
	An exception occurred while evaluating a constant
	at /Users/brian/.zef/store/META6.git/7304270f62587c723a9aa94ce6fd601770f7d3da/t/040-projects.t:8
	Exception details:
	  Could not find symbol '&Class'
		in block  at t/040-projects.t line 8

	===> Testing [FAIL]: META6:ver('0.0.11'):auth('github:jonathanstowe')
	Aborting due to test failure: META6:ver('0.0.11'):auth('github:jonathanstowe') (use --force-test to override)
	  in code  at /Applications/Rakudo/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 373
	  in method test at /Applications/Rakudo/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 351
	  in code  at /Applications/Rakudo/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 528
	  in sub  at /Applications/Rakudo/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 525
	  in method install at /Applications/Rakudo/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 631
	  in sub MAIN at /Applications/Rakudo/share/perl6/site/sources/ED3033E8712BCF9F6DE53678B14A54705DF211A6 (Zef::CLI) line 152
	  in block <unit> at /Applications/Rakudo/share/perl6/site/resources/6182CA1C8C9C6ED5BBB3076B522103070B37DDA4 line 1
	  in sub MAIN at /Applications/Rakudo/share/perl6/site/bin/zef line 2
	  in block <unit> at /Applications/Rakudo/share/perl6/site/bin/zef line 2

**Comment by jonathanstowe** [comment]
Hi,
That test failure was fixed with 0d0c2672720b095a7da1fbfdd8c9b191d5473c1c which was  20 December last year.

I guess that you have the older version in  zef's local cache which you can see with:

    zef search META6

You can force zef to install the specific version with:

    zef install 'META6:ver("0.0.16")'

But why zef is attempting to install an older version without checking there was a new one available is something that you probably want to check with @ugexe

**Comment by briandfoy** [comment]
It turns out to have been a zef problem: https://github.com/ugexe/zef/issues/199
