### ISSUE TITLE
method EXISTS-KEY should return a Bool

### ISSUE THREAD

**Issue by tbrowder** [jonathanstowe/META6#9]
I try to check the validity of a META6.json file:

```
my $file = 'META6.json.invalid';   # <== has a missing 'description' key
my $m = META6.new:  :$file;
for 'version', 'name', 'description' -> $k {
    die "missing key $k unless $m.EXISTS-KEY($k);
}
```

The code above doesn't throw as expected.  However, this does:

```
for 'version', 'name', 'description' -> $k {
    die "missing key $k unless $m.ATT-KEY($k);
}
```

**Comment by jonathanstowe** [comment]
Thanks for noticing.  I'll look at it this evening.

**Comment by jonathanstowe** [comment]
Ah I see how @gfldex implemented like that deliberately (that is it is a valid attribute.) but I still agree that it should return False if the attribute isn't set.

**Comment by tbrowder** [comment]
I noticed the enums for required, optional, customary and such, it would be useful to be able to test for that but I did not see an obvious way for me to do it.  Also, I asked earlier on #perl6 about updating META6.json specs but have seen no response yet.

**Comment by jonathanstowe** [comment]
You probably want to see how Test::META uses those traits.
